### ISSUE TITLE
Empty authorization header throws an exception

### ISSUE THREAD

**Issue by 4egod** [dotnet/systemweb-adapters#292]
Sending a request with an empty authorization header throws an exception

```
System.FormatException: The format of value '' is invalid.
   at System.Net.Http.Headers.HttpHeaderParser.ParseValue(String value, Object storeValue, Int32& index)
   at System.Net.Http.Headers.HttpHeaders.ParseAndAddValue(HeaderDescriptor descriptor, HeaderStoreItemInfo info, String value)
   at System.Net.Http.Headers.HttpHeaders.Add(HeaderDescriptor descriptor, IEnumerable`1 values)
   at System.Net.Http.Headers.HttpHeaders.Add(String name, IEnumerable`1 values)
   at Microsoft.AspNetCore.SystemWebAdapters.Authentication.RemoteAppAuthenticationService.AddHeaders(IEnumerable`1 headersToForward, HttpRequest originalRequest, HttpRequestMessage authRequest) in W:\Reasol\systemweb-adapters\src\Microsoft.AspNetCore.SystemWebAdapters.CoreServices\Authentication\RemoteAppAuthenticationService.cs:line 126
   at Microsoft.AspNetCore.SystemWebAdapters.Authentication.RemoteAppAuthenticationService.AuthenticateAsync(HttpRequest originalRequest, CancellationToken cancellationToken) in W:\Reasol\systemweb-adapters\src\Microsoft.AspNetCore.SystemWebAdapters.CoreServices\Authentication\RemoteAppAuthenticationService.cs:line 85
   at Microsoft.AspNetCore.SystemWebAdapters.Authentication.RemoteAppAuthenticationAuthHandler.GetRemoteAppAuthenticationResultAsync() in W:\Reasol\systemweb-adapters\src\Microsoft.AspNetCore.SystemWebAdapters.CoreServices\Authentication\RemoteAppAuthenticationAuthHandler.cs:line 48
   at Microsoft.AspNetCore.SystemWebAdapters.Authentication.RemoteAppAuthenticationAuthHandler.HandleAuthenticateAsync() in W:\Reasol\systemweb-adapters\src\Microsoft.AspNetCore.SystemWebAdapters.CoreServices\Authentication\RemoteAppAuthenticationAuthHandler.cs:line 66
   at Microsoft.AspNetCore.Authentication.AuthenticationHandler`1.AuthenticateAsync()
   at Microsoft.AspNetCore.Authentication.AuthenticationService.AuthenticateAsync(HttpContext context, String scheme)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)
```

**Comment by twsouthwick** [comment]
Fixed by #293
