### ISSUE TITLE
Net Core 8 Unable to resolve service for type 'Microsoft.AspNetCore.SystemWebAdapters.Authentication.IRemoteAppAuthenticationService' while trying to set up remote auth

### ISSUE THREAD

**Issue by lkneat** [dotnet/systemweb-adapters#517]
### Describe the bug
While trying to set up according to docs we get the following error when we try to visit a test endpoint on our .net core app

```
Unable to resolve service for type 'Microsoft.AspNetCore.SystemWebAdapters.Authentication.IRemoteAppAuthenticationService' while attempting to activate 'Microsoft.AspNetCore.SystemWebAdapters.Authentication.RemoteAppAuthenticationAuthHandler'`
```

This is happening in a closed company code base, I've included the systemwebadapters setup below and I'm currently working on reproducing in a minimal new .net core 8 app. 

I've had trouble finding any reports of similar errors so any guidance at all in figuring out the root issue would be greatly appreciated. The error occurs when just accessing the test endpoint on this .net core 8 app, the .net framework app is not set up. 

The .net core 8 app is set up with Yarp and we are accessing it via nginx normally. In order to reproduce I'm going straight to the app on the host port. The test endpoint is not interacting with yarp in any way it just returns some text

### To Reproduce
Using the Startup.Cs / Program.cs setup 

```cs
 services.AddSystemWebAdapters()
         .AddJsonSessionSerializer(_ =>
         {
            // Register every session key here
         })
         .AddRemoteAppClient(options =>
         {
            string apiKey = Configuration["ApiKey"];
            Uri remoteUrl = new(Configuration["ReverseProxy:Address"]);

            if (HostEnvironment.IsDevelopment())
            {
               HttpClientHandler dangerous = new HttpClientHandler { UseCookies = false, AllowAutoRedirect = false };

               dangerous.ServerCertificateCustomValidationCallback =
                  HttpClientHandler.DangerousAcceptAnyServerCertificateValidator;

               var dangerousClient = new HttpClient(dangerous);
               dangerousClient.BaseAddress = remoteUrl;
               dangerousClient.DefaultRequestHeaders.Add("X-SystemWebAdapter-RemoteAppAuthentication-Key", apiKey);
               options.BackchannelClient = dangerousClient;
            }

            options.RemoteAppUrl = remoteUrl;
            options.ApiKey = apiKey;
         }).AddAuthenticationClient(isDefaultScheme: true)  //setting to false prevents the error so I'm convinced it's related to auth
         .AddSessionClient();
         
         services.AddAuthorization()
         .AddAuthorizationHandlers(); //adds singletons for authorization handling using services.AddSingleton<IAuthorizationHandler, >
```

### Exceptions (if any)
```
fail: Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware[1]
      An unhandled exception has occurred while executing the request.
      System.InvalidOperationException: Unable to resolve service for type 'Microsoft.AspNetCore.SystemWebAdapters.Authentication.IRemoteAppAuthenticationService' while attempting to activate 'Microsoft.AspNetCore.SystemWebAdapters.Authentication.RemoteAppAuthenticationAuthHandler'.
         at Microsoft.Extensions.DependencyInjection.ActivatorUtilities.ConstructorMatcher.CreateInstance(IServiceProvider provider)
         at Microsoft.Extensions.DependencyInjection.ActivatorUtilities.CreateInstance(IServiceProvider provider, Type instanceType, Object[] parameters)
         at Microsoft.AspNetCore.Authentication.AuthenticationHandlerProvider.GetHandlerAsync(HttpContext context, String authenticationScheme)
         at Microsoft.AspNetCore.Authentication.AuthenticationService.AuthenticateAsync(HttpContext context, String scheme)
         at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
         at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddlewareImpl.Invoke(HttpContext context)
fail: Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware[1]
      An unhandled exception has occurred while executing the request.
      System.InvalidOperationException: Unable to resolve service for type 'Microsoft.AspNetCore.SystemWebAdapters.Authentication.IRemoteAppAuthenticationService' while attempting to activate 'Microsoft.AspNetCore.SystemWebAdapters.Authentication.RemoteAppAuthenticationAuthHandler'.
         at Microsoft.Extensions.DependencyInjection.ActivatorUtilities.ConstructorMatcher.CreateInstance(IServiceProvider provider)
         at Microsoft.Extensions.DependencyInjection.ActivatorUtilities.CreateInstance(IServiceProvider provider, Type instanceType, Object[] parameters)
         at Microsoft.AspNetCore.Authentication.AuthenticationHandlerProvider.GetHandlerAsync(HttpContext context, String authenticationScheme)
         at Microsoft.AspNetCore.Authentication.AuthenticationService.AuthenticateAsync(HttpContext context, String scheme)
         at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
         at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddlewareImpl.Invoke(HttpContext context)
```

### Further technical details 

Please include the following if applicable:

*ASP.NET Framework Application*: 
- Technologies and versions used (i.e. MVC/WebForms/etc): Webforms, MVC, Server side rendering
- .NET Framework Version: 4.7.2
- IIS Version: 10.0.22611.1
- Windows Version: 11

*ASP.NET Core Application*:
- Targeted .NET version: 8.0
- .NET SDK version: 8.0

**Comment by twsouthwick** [comment]
@lkneat I can't repro this - if you can get a solution that can be run to repro it, I'll take  a look

**Comment by lkneat** [comment]
Thank you for the response. and for trying to reproduce! 

While trying to reproduce we traced it back to Unity DI which we had added to the .net core app temporarily to try and get our dependencies over quickly. 

Apologies for the time this may have taken up, really appreciate it

**Comment by twsouthwick** [comment]
thanks for the follow up!
