### ISSUE TITLE
Unable to load remote session state for session xxxxxx

### ISSUE THREAD

**Issue by thiha-the-great** [dotnet/systemweb-adapters#535]
### Describe the bug
I have established session sharing between .NET Core and .NET Framework, and the application works well as expected. However, after some time, I needed to develop a new page. This page contains a table with around 40 rows, and each row triggers a backend API call when the page loads. As a result, it takes a while to load. When I close the browser or navigate back to the previous page during loading, an exception error occurs (see exception session). Is there anyway that I can manually handle user interaction exception? 

### Exceptions (if any)
Unable to load remote session state for session xxxxxxxxxxxxxxx
System.Threading.Tasks.TaskCanceledException: The operation was canceled.
 ---> System.IO.IOException: Unable to read data from the transport connection: The I/O operation has been aborted because of either a thread exit or an application request..
 ---> System.Net.Sockets.SocketException (995): The I/O operation has been aborted because of either a thread exit or an application request.
   --- End of inner exception stack trace ---
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.ThrowException(SocketError error, CancellationToken cancellationToken)
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.System.Threading.Tasks.Sources.IValueTaskSource<System.Int32>.GetResult(Int16 token)
   at System.Net.Http.HttpConnection.SendAsyncCore(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at System.Net.Http.HttpClient.HandleFailure(Exception e, Boolean telemetryStarted, HttpResponseMessage response, CancellationTokenSource cts, CancellationToken cancellationToken, CancellationTokenSource pendingRequestsCts)
   at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationTokenSource cts, Boolean disposeCts, CancellationTokenSource pendingRequestsCts, CancellationToken originalCancellationToken)
   at Microsoft.AspNetCore.SystemWebAdapters.SessionState.RemoteSession.RemoteAppSessionStateManager.GetSessionDataAsync(String sessionId, Boolean readOnly, HttpContext callingContext, CancellationToken token)
   at Microsoft.AspNetCore.SystemWebAdapters.SessionState.RemoteSession.RemoteAppSessionStateManager.CreateAsync(HttpContext context, SessionAttribute metadata)

### Further technical details 

Please include the following if applicable:

*ASP.NET Framework Application*:
- Technologies and versions used (i.e. MVC/WebForms/etc): MVC
- .NET Framework Version: 4.7.2
- IIS Version: 10
- Windows Version: 11 Pro

*ASP.NET Core Application*:
- Targeted .NET version: 6
- .NET SDK version: 6

**Comment by joperezr** [comment]
Thanks for the report @thiha-the-great. In order to be able take a closer look, would you happen to have a simplified repro? That would allow us to diagnose what is going on and understand where the error is happening and how to handle it.
