### ISSUE TITLE
The controller for path '/systemweb-adapters/authenticate' was not found or does not implement IController

### ISSUE THREAD

**Issue by tbertenshaw** [dotnet/systemweb-adapters#77]
Using [the blog post](https://devblogs.microsoft.com/dotnet/incremental-asp-net-migration-tooling-preview-2/) i was able to successfully get the authentication working on brand new sample app.

However when i tried to plug it into my legacy aspnet framework mvc app i got the following error, from the .Net core app.

```
System.IO.EndOfStreamException: Unable to read beyond the end of the stream.
   at System.IO.BinaryReader.InternalRead(Int32 numBytes)
   at System.IO.BinaryReader.ReadInt32()
   at System.Security.Claims.ClaimsPrincipal..ctor(BinaryReader reader)
   at Microsoft.AspNetCore.SystemWebAdapters.Authentication.RemoteAppAuthenticationResultFactory.CreateRemoteAppAuthenticationResultAsync(HttpResponseMessage response, RemoteAppAuthenticationOptions options)
   at Microsoft.AspNetCore.SystemWebAdapters.Authentication.RemoteAppAuthenticationService.AuthenticateAsync(HttpRequest originalRequest, CancellationToken cancellationToken)
   at Microsoft.AspNetCore.SystemWebAdapters.Authentication.RemoteAppAuthenticationAuthHandler.GetRemoteAppAuthenticationResultAsync()
   at Microsoft.AspNetCore.SystemWebAdapters.Authentication.RemoteAppAuthenticationAuthHandler.HandleAuthenticateAsync()
   at Microsoft.AspNetCore.Authentication.AuthenticationHandler`1.AuthenticateAsync()
   at Microsoft.AspNetCore.Authentication.AuthenticationService.AuthenticateAsync(HttpContext context, String scheme)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)
```

I have found the following in the debug output of the .NET Framework app

`The controller for path '/systemweb-adapters/authenticate' was not found or does not implement IController
`
*ASP.NET Framework Application*:
- Technologies and versions used (i.e. MVC/WebForms/etc): MVC 5,WebApi, Autofac
- .NET Framework Version: NET 4.72
- IIS Version: Both  IIS with a CNAME and IISexpress (Same error)
- Windows Version: 11

*ASP.NET Core Application*:
- Targeted .NET version: 6
- .NET SDK version:  6

**Comment by tbertenshaw** [comment]
Found and resolved the issue. For some reason installing the `SystemWebAdapters` nuget package didn't add/merge the following into the existing section in the `web.config`

```xml
 <system.webServer>
   <modules>
     <remove name="SystemWebAdapterModule" />
     <add name="SystemWebAdapterModule" type="Microsoft.AspNetCore.SystemWebAdapters.SystemWebAdapterModule, Microsoft.AspNetCore.SystemWebAdapters" preCondition="managedHandler" />
    </modules>
 </system.webServer>
```
