### ISSUE TITLE
YARP Proxy Not Working With IIS Express

### ISSUE THREAD

**Issue by bsulliva** [dotnet/systemweb-adapters#79]
I'm able to load the new .net core endpoints like / and /home/privacy, but any requests back to my old .net MVC application, I'm just getting an error in the browser, "This page isn't working right now".

In the launchsettings.json I see the following. Both the old and new sites are indepentely accessible, I just can't access both sites through https://localhost:7266. 
```
"profiles": {
    "Mouser_Web.Core": {
      "commandName": "Project",
      "dotnetRunMessages": true,
      "launchBrowser": true,
      "applicationUrl": "https://localhost:7266;http://localhost:5266",
      "environmentVariables": {
        "ASPNETCORE_ENVIRONMENT": "Development",
        "ReverseProxy__Clusters__fallbackCluster__Destinations__fallbackApp__Address": "https://www.oldsite.com:44333"
      }
    },
```

Is anything supposed to be filled out in the appsettings.json file in fallbackApp/Address section? And the Path is supposed to be **catch-all?

```
    "ReverseProxy": {
    "Routes": {
      "fallbackRoute": {
        "ClusterId": "fallbackCluster",
        "Order": "1",
        "Match": {
          "Path": "{**catch-all}"
        }
      }
    },
    "Clusters": {
      "fallbackCluster": {
        "Destinations": {
          "fallbackApp": {
            "Address": ""
          }
        }
      }
    }
```

*ASP.NET Framework Application*:
We are running .net 4.8 site with a mixture of MVC and Web Forms running out of the application. This old site uses IIS Express

*ASP.NET Core Application*:
.Net 6.0

**Comment by bsulliva** [comment]
In the VS Debugger console window, I see SSL errors when trying to do the reverse proxy. Is there a way to resolve the SSL errors?

info: Yarp.ReverseProxy.Forwarder.HttpForwarder[9]
      Proxying to https://www.mdev.com:44333/MyAccount/MLogin HTTP/2 RequestVersionOrLower no-streaming
info: Yarp.ReverseProxy.Forwarder.HttpForwarder[48]
      Request: An error was encountered before receiving a response.
      System.Net.Http.HttpRequestException: The SSL connection could not be established, see inner exception.
       ---> System.Security.Authentication.AuthenticationException: The remote certificate is invalid according to the validation procedure: RemoteCertificateNameMismatch
         at System.Net.Security.SslStream.SendAuthResetSignal(ProtocolToken message, ExceptionDispatchInfo exception)
         at System.Net.Security.SslStream.CompleteHandshake(SslAuthenticationOptions sslAuthenticationOptions)
         at System.Net.Security.SslStream.ForceAuthenticationAsync[TIOAdapter](TIOAdapter adapter, Boolean receiveFirst, Byte[] reAuthenticationData, Boolean isApm)
         at System.Net.Http.ConnectHelper.EstablishSslConnectionAsync(SslClientAuthenticationOptions sslOptions, HttpRequestMessage request, Boolean async, Stream stream, CancellationToken cancellationToken)
         --- End of inner exception stack trace ---
         at System.Net.Http.ConnectHelper.EstablishSslConnectionAsync(SslClientAuthenticationOptions sslOptions, HttpRequestMessage request, Boolean async, Stream stream, CancellationToken cancellationToken)
         at System.Net.Http.HttpConnectionPool.ConnectAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
         at System.Net.Http.HttpConnectionPool.AddHttp2ConnectionAsync(HttpRequestMessage request)
         at System.Threading.Tasks.TaskCompletionSourceWithCancellation`1.WaitWithCancellationAsync(CancellationToken cancellationToken)
         at System.Net.Http.HttpConnectionPool.GetHttp2ConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
         at System.Net.Http.HttpConnectionPool.SendWithVersionDetectionAndRetryAsync(HttpRequestMessage request, Boolean async, Boolean doRequestAuth, CancellationToken cancellationToken)
         at System.Net.Http.DiagnosticsHandler.SendAsyncCore(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
         at Yarp.ReverseProxy.Forwarder.HttpForwarder.SendAsync(HttpContext context, String destinationPrefix, HttpMessageInvoker httpClient, ForwarderRequestConfig requestConfig, HttpTransformer transformer)

**Comment by twsouthwick** [comment]
Looks like it has to do with SSL cert validation. Are you using a self-signed cert here?

@Tratcher what's the recommendation for SSL with YARP proxying?

**Comment by bsulliva** [comment]
When I first did the migration and the .net core project was installed, then started debugging, it presented me with an option of using a self signed cert for the .net core piece I believe. I think I chose use the self signed cert, but I'm not sure how to bring that option to choose back up or where that option is saved.

**Comment by Tratcher** [comment]
YARP is trying to proxy to `www.mdev.com` but `RemoteCertificateNameMismatch` means that IIS isn't returning a certificate that matches that host name. Can you access the site directly using that url?

If you're using IIS Express locally then its developer certificate only works for requests to `localhost`. Are you using a hosts file to remap `www.mdev.com` to a local server?

One way to work around this in a development environment is to set: DangerousAcceptAnyServerCertificate
https://microsoft.github.io/reverse-proxy/articles/config-files.html

**Comment by bsulliva** [comment]
Yes I can pull up both the .net core site and www.mdev.com locally. Now Edge does stop the site from being pulled up and I have to manually say its ok to bypass the invalid cert for mdev.com. For debugging locally, yes we use the hosts file to map mdev.com back to localhost (127.0.0.1). I'll try out the DnagerousAcceptAnyServerCertificate option. As far as the initial prompt I saw to use the self signed cert for the new .net core site, do you know how to change that option to something other than a self-signed cert?

**Comment by bsulliva** [comment]
I tried setting it to true, but getting the same error. It looks like it goes in the Clusters section?

```
"Clusters": {
      "fallbackCluster": {
        "Destinations": {
          "fallbackApp": {
            "Address": ""
          }
        }
      },
      "HttpClient": { // Configuration of HttpClient instance used to contact destinations
        "DangerousAcceptAnyServerCertificate": true
      }
    }
```

**Comment by Tratcher** [comment]
IIS Express can only be used with a self-signed cert. Kestrel's dev cert can be replaced in code or via config.
https://docs.microsoft.com/en-us/aspnet/core/fundamentals/servers/kestrel/endpoints?view=aspnetcore-6.0

**Comment by Tratcher** [comment]
Try:
```
   "Clusters": {
      "fallbackCluster": {
        "Destinations": {
          "fallbackApp": {
            "Address": ""
          }
        },
        "HttpClient": { // Configuration of HttpClient instance used to contact destinations
          "DangerousAcceptAnyServerCertificate": true
        }
      }
    }
```

**Comment by bsulliva** [comment]
Thanks @Tratcher that fixed it
