### ISSUE TITLE
Getting "Serialized session state has different version than expected" error when attempting to utilize Session.

### ISSUE THREAD

**Issue by ahazelwood** [dotnet/systemweb-adapters#85]
### Describe the bug
I have setup my 2 projects (1 asp.net web forms app, and 1 asp.net core Razor Pages app).

When I attempt to force the usage of Session state to all pages, I get the exception noted below.

### To Reproduce

asp.net core is configured as:  

```
            builder.Services.AddSystemWebAdapters()
                .AddJsonSessionSerializer(options => {
                    options.RegisterKey<int>("LookupKey");
                    //RemoteServiceUtils.RegisterSessionKeys(options.KnownKeys);
                })
                .AddRemoteAppSession(options => {
                    options.RemoteAppUrl = new Uri(builder.Configuration["ReverseProxy:Clusters:fallbackCluster:Destinations:fallbackApp:Address"]);
                    options.ApiKey = RemoteServiceUtils.ApiKey;
                })
                .AddRemoteAppAuthentication(true, options => {
                    options.RemoteServiceOptions.RemoteAppUrl = new Uri(builder.Configuration["ReverseProxy:Clusters:fallbackCluster:Destinations:fallbackApp:Address"]);
                    options.RemoteServiceOptions.ApiKey = RemoteServiceUtils.ApiKey;
                });
```

asp.net web forms project is configured as:
```
			Application.AddSystemWebAdapters()
				.AddProxySupport(options => {
					options.UseForwardedHeaders = true;
				})
				.AddRemoteAppAuthentication(options => {
					options.RemoteServiceOptions.ApiKey = RemoteServiceUtils.ApiKey;
				})
				.AddRemoteAppSession(options => {
					options.ApiKey = RemoteServiceUtils.ApiKey;
				}, options => {
					//RemoteServiceUtils.RegisterSessionKeys(options.KnownKeys);
					options.RegisterKey<int>("LookupKey");
                });


            app.MapRazorPages()
                .RequireSystemWebAdapterSession();
```

If I do not force the Session usage, the proxying works as I would expect.  Session state is using the Microsoft.Web.Redis.RedisSessionStateProvider, so potentially that is causing some issues?  

### Exceptions (if any)

```
info: Yarp.ReverseProxy.Configuration.ConfigProvider.ConfigurationConfigProvider[1]
      Loading proxy data from config.
info: Microsoft.Hosting.Lifetime[14]
      Now listening on: https://localhost:7109
info: Microsoft.Hosting.Lifetime[14]
      Now listening on: http://localhost:5109
info: Microsoft.Hosting.Lifetime[0]
      Application started. Press Ctrl+C to shut down.
info: Microsoft.Hosting.Lifetime[0]
      Hosting environment: Development
info: Microsoft.Hosting.Lifetime[0]
      Content root path: D:\projects\4.5.6\source\websites\dashboards\CI.Website.Analysts.Core\
info: System.Net.Http.HttpClient.IRemoteAppAuthenticationService.LogicalHandler[100]
      Start processing HTTP request GET https://localhost:44300/systemweb-adapters/authenticate
info: System.Net.Http.HttpClient.IRemoteAppAuthenticationService.ClientHandler[100]
      Sending HTTP request GET https://localhost:44300/systemweb-adapters/authenticate
info: System.Net.Http.HttpClient.IRemoteAppAuthenticationService.ClientHandler[101]
      Received HTTP response headers after 29.7402ms - 302
info: System.Net.Http.HttpClient.IRemoteAppAuthenticationService.LogicalHandler[101]
      End processing HTTP request after 34.2488ms - 302
info: System.Net.Http.HttpClient.ISessionManager.LogicalHandler[100]
      Start processing HTTP request GET https://localhost:44300/systemweb-adapters/session
info: System.Net.Http.HttpClient.ISessionManager.ClientHandler[100]
      Sending HTTP request GET https://localhost:44300/systemweb-adapters/session
info: System.Net.Http.HttpClient.ISessionManager.ClientHandler[101]
      Received HTTP response headers after 29.5322ms - 200
info: System.Net.Http.HttpClient.ISessionManager.LogicalHandler[101]
      End processing HTTP request after 29.6101ms - 200
fail: Microsoft.AspNetCore.SystemWebAdapters.SessionState.RemoteSession.RemoteAppSessionStateManager[1]
      Unable to load remote session state for session rbhmqjyyln3ycfpwcab5blqj
      System.InvalidOperationException: Serialized session state has different version than expected
         at Microsoft.AspNetCore.SystemWebAdapters.SessionState.Serialization.BinarySessionSerializer.Read(BinaryReader reader)
         at Microsoft.AspNetCore.SystemWebAdapters.SessionState.Serialization.BinarySessionSerializer.DeserializeAsync(Stream stream, CancellationToken token)
         at Microsoft.AspNetCore.SystemWebAdapters.SessionState.RemoteSession.RemoteAppSessionStateManager.GetSessionDataAsync(String sessionId, Boolean readOnly, HttpContext callingContext, CancellationToken token)
         at Microsoft.AspNetCore.SystemWebAdapters.SessionState.RemoteSession.RemoteAppSessionStateManager.CreateAsync(HttpContext context, ISessionMetadata metadata)
fail: Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware[1]
      An unhandled exception has occurred while executing the request.
      System.InvalidOperationException: Serialized session state has different version than expected
         at Microsoft.AspNetCore.SystemWebAdapters.SessionState.Serialization.BinarySessionSerializer.Read(BinaryReader reader)
         at Microsoft.AspNetCore.SystemWebAdapters.SessionState.Serialization.BinarySessionSerializer.DeserializeAsync(Stream stream, CancellationToken token)
         at Microsoft.AspNetCore.SystemWebAdapters.SessionState.RemoteSession.RemoteAppSessionStateManager.GetSessionDataAsync(String sessionId, Boolean readOnly, HttpContext callingContext, CancellationToken token)
         at Microsoft.AspNetCore.SystemWebAdapters.SessionState.RemoteSession.RemoteAppSessionStateManager.CreateAsync(HttpContext context, ISessionMetadata metadata)
         at Microsoft.AspNetCore.SystemWebAdapters.SessionMiddleware.ManageStateAsync(HttpContext context, ISessionMetadata metadata)
         at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
         at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
         at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)

```

### Further technical details 

Please include the following if applicable:

*ASP.NET Framework Application*:
- Technologies and versions used (i.e. MVC/WebForms/etc): Web Forms
- .NET Framework Version:  4.8
- IIS Version:  IIS Express
- Windows Version:  Windows 11

*ASP.NET Core Application*:
- Targeted .NET version:  .net 6.0
- .NET SDK version:

**Comment by twsouthwick** [comment]
@ahazelwood can you verify you have preview2 installed on both? The format is different from preview1

**Comment by ahazelwood** [comment]
I’m working on getting a standalone solution for this.  I should have it later on this afternoon.

Thanks.

**Comment by ahazelwood** [comment]
In my testbed project, it is working as expected, so there must be something else that is occurring within our existing asp.net web forms project.

I'll close for now, although some additional logging would be useful.  

Thanks.

**Comment by twsouthwick** [comment]
@gumbarros do you have the same version on framework and core?

**Comment by gumbarros** [comment]
@twsouthwick  yes, both are at the same version
![image](https://user-images.githubusercontent.com/52143624/187735168-528e5dcf-2b95-4595-9ee6-505fe529f8a6.png)

DanSales.Core is the .NET Core website and DanSales.Web the VB.NET WebForms one.

Program.cs
```cs
static void ConfigureSystemWebAdapters(WebApplicationBuilder builder)
{
    builder.Services.AddSystemWebAdapters().AddRemoteApp(options =>
    {
        options.RemoteAppUrl = new(builder.Configuration["ReverseProxy:Clusters:fallbackCluster:Destinations:fallbackApp:Address"]);
        options.ApiKey = SessionUtils.SessionApiKey;
    })
    .AddRemoteAppSession()
    .AddJsonSessionSerializer(options =>
    {
        SessionUtils.RegisterKeys(options.KnownKeys);
    });
}
```
Global.asax.vb
```vb
	Private Sub RegisterSystemWebAdapters()
		SystemWebAdapterConfiguration.AddSystemWebAdapters(Me) _
		.AddProxySupport(Sub(options)
							 options.UseForwardedHeaders = True
						 End Sub) _
		.AddRemoteApp(Sub(options)
						  options.ApiKey = SessionUtils.SessionApiKey
					  End Sub) _
		.AddRemoteAppSession() _
		.AddRemoteAppAuthentication() _
		.AddJsonSessionSerializer(Sub(options)
									  SessionUtils.RegisterKeys(options.KnownKeys)
								  End Sub)
	End Sub
```

If I set a cookie name for both, the error don't happen, but the session values are not shared.

**Comment by gumbarros** [comment]
I found in the application logs, this exception.
```
31/08/2022 13:51:09 (Error)
Error Caught in Global_Error event
Error in: https://localhost:44325/systemweb-adapters/session
Error Message:The specified type System.RuntimeType must derive from the specific value's type System.String.
Stack Trace:   at System.Text.Json.ThrowHelper.ThrowArgumentException_DeserializeWrongType(Type type, Object value)
   at System.Text.Json.JsonSerializer.GetRuntimeTypeAndValidateInputType(Object value, Type inputType)
   at System.Text.Json.JsonSerializer.SerializeToUtf8Bytes(Object value, Type inputType, JsonSerializerOptions options)
   at Microsoft.AspNetCore.SystemWebAdapters.SessionState.Serialization.JsonSessionKeySerializer.TrySerialize(String key, Object value, Byte[]& bytes) in /_/src/Microsoft.AspNetCore.SystemWebAdapters.SessionState/Serialization/JsonSessionKeySerializer.Shared.cs:line 33
   at Microsoft.AspNetCore.SystemWebAdapters.SessionState.Serialization.BinarySessionSerializer.Write(ISessionState state, BinaryWriter writer) in /_/src/Microsoft.AspNetCore.SystemWebAdapters.SessionState/Serialization/BinarySessionSerializer.Shared.cs:line 72
   at Microsoft.AspNetCore.SystemWebAdapters.SessionState.Serialization.BinarySessionSerializer.SerializeAsync(ISessionState state, Stream stream, CancellationToken token) in /_/src/Microsoft.AspNetCore.SystemWebAdapters.SessionState/Serialization/BinarySessionSerializer.Shared.cs:line 155
   at Microsoft.AspNetCore.SystemWebAdapters.SessionState.RemoteSession.GetWriteableSessionHandler.<ProcessRequestAsync>d__6.MoveNext() in /_/src/Microsoft.AspNetCore.SystemWebAdapters.SessionState/RemoteSession/Framework/GetWriteableSessionHandler.cs:line 53
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.SystemWebAdapters.SessionState.RemoteSession.GetWriteableSessionHandler.<ProcessRequestAsync>d__5.MoveNext() in /_/src/Microsoft.AspNetCore.SystemWebAdapters.SessionState/RemoteSession/Framework/GetWriteableSessionHandler.cs:line 34
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Web.TaskAsyncHelper.EndTask(IAsyncResult ar)
   at System.Web.HttpApplication.CallHandlerExecutionStep.System.Web.HttpApplication.IExecutionStep.Execute()
   at System.Web.HttpApplication.ExecuteStepImpl(IExecutionStep step)
   at System.Web.HttpApplication.ExecuteStep(IExecutionStep step, Boolean& completedSynchronously)
```

Registred my key with object instead of string and solved my problem.

Also added AddSessionSerializer to both builders.

**Comment by twsouthwick** [comment]
Ah - that's interesting. I'm going to great a new issue for that. We shiuld handle that case better
